version: "3.9"
services:
  story_service:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "4002:4002"
    volumes:
      - ..:/workdir
      - /workdir/node_modules
    command: sleep infinity
